title: "My Jekyll Blog Page"
subtitle: "Blog Entries"
github:
  user: "0x007e"
  email: "person@mail.address"
copyright: "Created by 0x007E"
license: "https://github.com/0x007e/tilde/LICENSE.md"

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

url: "https://0x007e.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: 0x007e/tilde

social:
  - title: Tilde Theme repository at GitHub
    icon: github
    link: "https://github.com/?"
    # values: primary, secondary, success, danger, warning, info, light, dark, body-emphasis
    color: "danger"
  - title: Tilde Theme repository at GitLab
    icon: gitlab
    link: "https://gitlab.com/?"
  - title: 0x007e at X (formerly Twitter)
    icon: x
    link: "https://x.com/?"
  - title: 0x007e at LinkedIn
    icon: linkedin
    link: "www.linkedin.com/in/?"
  - title: 0x007e on WhatsApp
    icon: whatsapp
    link: "www.whatsapp.com/?"
  ### and many more -> https://tabler.io/icons -> search: brand

tilde:
  # Restict links in navbar to listed pages
  # nav_pages:
  #   - about.md
  # date_format: "%b %-d, %Y"
  show_introduction: true
  visible_posts: 2
  category_show_goto: true
  truncate_next_blog_link: 35

# footer:
# Column allocation in the footer. A total of 10 is always required.
#   github_column: 4
#   description_column: 6


feed:
  hide: false
  color: "success"

#google_analytics: "UA-XXXXXXXXX-X" # Google Analytics tracking ID

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false 

sass:
  style: compressed

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false