title: "Jekyll Tilde Theme"
# If brand is not set the github user avatar will be used.
# Priority:
# - image
# - gravatar
# - github user avatar
brand:
  # image: "https://image.url/here.png"
  # Mail SHA256 encrypted with https://emn178.github.io/online-tools/sm3.html
  gravatar: "f4ef9cbf3c2c5a2a1afa89a33134b335b5237132f06729990cacbfc5646b0b6a"
  # width: 20   # default: 30
  # height: 20  # default: 30
github:
  user: "0x007e"
  # email: "person@mail.address"
copyright: "Distributed by 0x007E"
license: "https://github.com/0x007E/jekyll-tilde-theme/blob/main/LICENSE.md"

description: >
  The theme is to write blog posts, either in categories or a single collection of
  posts. It is not designed to write a documentation. It uses bootstrap 5 and is
  fully responsive. Also code blocks with syntax highlighting are supported.
  The theme is designed to be used with Jekyll and GitHub Pages.

url: "https://0x007e.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jekyll-tilde-theme" # the subpath of your site, e.g. /blog
remote_theme: 0x007e/tilde

social:
  - title: Tilde Theme repository at GitHub
    icon: github
    link: "https://github.com/?"
    # values: primary, secondary, success, danger, warning, info, light, dark, body-emphasis
    color: "danger"
  - title: Tilde Theme repository at GitLab
    icon: gitlab
    link: "https://gitlab.com/?"
  - title: 0x007e at X (formerly Twitter)
    icon: x
    link: "https://x.com/?"
  - title: 0x007e at LinkedIn
    icon: linkedin
    link: "www.linkedin.com/in/?"
  - title: 0x007e on WhatsApp
    icon: whatsapp
    link: "www.whatsapp.com/?"
  ### and many more -> https://tabler.io/icons -> search: brand

tilde:
  # Restict links in navbar to listed pages
  # -> e.g. if you have a README.md/LICENSE.md in your root folder and they should not be displayed.
  nav_pages:
    - about.md
    - impressum.md
  # Set in which formate dates are displayed
  # Possible formats: https://shopify.github.io/liquid/filters/date/
  # date_format: "%b %-d, %Y"
  show_introduction: true
  visible_posts: 4
  category_show_goto: true
  truncate_next_blog_link: 35

# footer:
# Column allocation in the footer. A total of 10 is always required.
#   github_column: 4
#   description_column: 6

feed:
  hide: false
  color: "success"

# google_analytics: "G-XXXXXXXXXX" # Google Analytics tracking ID
# cookies:
#   title: Cookies & Privacy
#   text: >
#     This website uses cookies for analysis and personalization (Google Analytics).
#     Should cookies be allowed?
#   button_accept: Accept
#   button_decline: Decline

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false 

sass:
  style: compressed

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false